using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Shared.Infrastructure.Migrations;

/// <inheritdoc />
public partial class Migration002_SeedData : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.InsertData(
            table: "Users",
            columns: new[] { "UserId", "Username", "Email", "Password", "Role", "Enabled" },
            values: new object[] { 1, "DbSeeder", "root@edimus.com", "$2a$11$RKOjo9jGUALtqDkaX52cj.7x8kcEj4mG4ESnP6i6Da9zc9DLE8wx.", 4, true });

        migrationBuilder.InsertData(
            table: "Companies",
            columns: new[] { "CompanyId", "Name", "Slogan", "Slug", "ReactiveStock", "PublicPrices", "PublicOrders", "Enabled" },
            values: new object[] { 1, "Maria Antonieta", "Universo Deli", "maria-antonieta", true, true, true, true });

        migrationBuilder.InsertData(
            table: "Categories",
            columns: new[] { "CategoryId", "CompanyId", "Name", "Enabled" },
            values: new object[,]
            {
                { 1, 1, "Cafetería", true },
                { 2, 1, "Pastelería", true },
                { 3, 1, "Especialidades", true },
                { 4, 1, "Combos", true },
                { 5, 1, "Almuerzos", true },
                { 6, 1, "Bebidas", true },
                { 7, 1, "Coctelería", true }
            });

        migrationBuilder.InsertData(
            table: "Premises",
            columns: new[] { "PremiseId", "CompanyId", "Name", "Enabled" },
            values: new object[] { 1, 1, "Barrio Jardin", true });

        migrationBuilder.InsertData(
            table: "Layouts",
            columns: new[] { "LayoutId", "PremiseId", "Name", "Height", "Width", "Enabled" },
            values: new object[] { 1, 1, "Planta Baja", 24, 24, true });

        migrationBuilder.InsertData(
            table: "Sectors",
            columns: new[] { "SectorId", "LayoutId", "Name", "Color", "PositionX", "PositionY", "Enabled" },
            values: new object[,]
            {
                { 1, 1, "Deck", "#EE82EE", 0, 0, true },
                { 2, 1, "Salon", "#FFA208", 0, 4, true },
                { 3, 1, "Patio Interno", "#FAC8C0", 0, 8, true },
                { 4, 1, "Garden", "#00FFFF", 12, 4, true },
                { 5, 1, "Patio Externo", "#00FF00", 0, 16, true }
            });

        migrationBuilder.InsertData(
            table: "SectorCoords",
            columns: new[] { "SectorId", "X", "Y" },
            values: new object[,]
            {
                { 1, 0, 0 },
                { 2, 0, 0 },
                { 3, 0, 0 },
                { 4, 0, 0 },
                { 5, 0, 0 },
                { 1, 0, 1 },
                { 2, 0, 1 },
                { 3, 0, 1 },
                { 4, 0, 1 },
                { 5, 0, 1 },
                { 1, 0, 2 },
                { 2, 0, 2 },
                { 3, 0, 2 },
                { 4, 0, 2 },
                { 5, 0, 2 },
                { 3, 0, 3 },
                { 4, 0, 3 },
                { 5, 0, 3 },
                { 3, 0, 4 },
                { 4, 0, 4 },
                { 3, 0, 5 },
                { 4, 0, 5 },
                { 3, 0, 6 },
                { 4, 0, 6 },
                { 4, 0, 7 },
                { 4, 0, 8 },
                { 4, 0, 9 },
                { 4, 0, 10 },
                { 1, 1, 0 },
                { 2, 1, 0 },
                { 3, 1, 0 },
                { 4, 1, 0 },
                { 5, 1, 0 },
                { 1, 1, 1 },
                { 2, 1, 1 },
                { 3, 1, 1 },
                { 4, 1, 1 },
                { 5, 1, 1 },
                { 1, 1, 2 },
                { 2, 1, 2 },
                { 3, 1, 2 },
                { 4, 1, 2 },
                { 5, 1, 2 },
                { 3, 1, 3 },
                { 4, 1, 3 },
                { 5, 1, 3 },
                { 3, 1, 4 },
                { 4, 1, 4 },
                { 3, 1, 5 },
                { 4, 1, 5 },
                { 3, 1, 6 },
                { 4, 1, 6 },
                { 4, 1, 7 },
                { 4, 1, 8 },
                { 4, 1, 9 },
                { 4, 1, 10 },
                { 1, 2, 0 },
                { 2, 2, 0 },
                { 3, 2, 0 },
                { 4, 2, 0 },
                { 5, 2, 0 },
                { 1, 2, 1 },
                { 2, 2, 1 },
                { 3, 2, 1 },
                { 4, 2, 1 },
                { 5, 2, 1 },
                { 1, 2, 2 },
                { 2, 2, 2 },
                { 3, 2, 2 },
                { 4, 2, 2 },
                { 5, 2, 2 },
                { 3, 2, 3 },
                { 4, 2, 3 },
                { 5, 2, 3 },
                { 3, 2, 4 },
                { 4, 2, 4 },
                { 3, 2, 5 },
                { 4, 2, 5 },
                { 3, 2, 6 },
                { 4, 2, 6 },
                { 4, 2, 7 },
                { 4, 2, 8 },
                { 4, 2, 9 },
                { 4, 2, 10 },
                { 2, 3, 0 },
                { 3, 3, 0 },
                { 4, 3, 0 },
                { 5, 3, 0 },
                { 1, 3, 1 },
                { 2, 3, 1 },
                { 3, 3, 1 },
                { 4, 3, 1 },
                { 5, 3, 1 },
                { 2, 3, 2 },
                { 3, 3, 2 },
                { 4, 3, 2 },
                { 5, 3, 2 },
                { 3, 3, 3 },
                { 4, 3, 3 },
                { 5, 3, 3 },
                { 3, 3, 4 },
                { 4, 3, 4 },
                { 3, 3, 5 },
                { 4, 3, 5 },
                { 3, 3, 6 },
                { 4, 3, 6 },
                { 4, 3, 7 },
                { 4, 3, 8 },
                { 4, 3, 9 },
                { 4, 3, 10 },
                { 1, 4, 0 },
                { 2, 4, 0 },
                { 3, 4, 0 },
                { 5, 4, 0 },
                { 1, 4, 1 },
                { 2, 4, 1 },
                { 3, 4, 1 },
                { 5, 4, 1 },
                { 1, 4, 2 },
                { 2, 4, 2 },
                { 3, 4, 2 },
                { 5, 4, 2 },
                { 3, 4, 3 },
                { 5, 4, 3 },
                { 3, 4, 4 },
                { 3, 4, 5 },
                { 3, 4, 6 },
                { 1, 5, 0 },
                { 2, 5, 0 },
                { 5, 5, 0 },
                { 1, 5, 1 },
                { 2, 5, 1 },
                { 5, 5, 1 },
                { 1, 5, 2 },
                { 2, 5, 2 },
                { 5, 5, 2 },
                { 5, 5, 3 },
                { 1, 6, 0 },
                { 2, 6, 0 },
                { 5, 6, 0 },
                { 1, 6, 1 },
                { 2, 6, 1 },
                { 5, 6, 1 },
                { 1, 6, 2 },
                { 2, 6, 2 },
                { 5, 6, 2 },
                { 2, 6, 3 },
                { 5, 6, 3 },
                { 2, 6, 4 },
                { 2, 6, 5 },
                { 2, 6, 6 },
                { 2, 6, 7 },
                { 2, 6, 8 },
                { 2, 6, 9 },
                { 2, 6, 10 },
                { 1, 7, 0 },
                { 2, 7, 0 },
                { 5, 7, 0 },
                { 1, 7, 1 },
                { 2, 7, 1 },
                { 5, 7, 1 },
                { 1, 7, 2 },
                { 2, 7, 2 },
                { 5, 7, 2 },
                { 2, 7, 3 },
                { 5, 7, 3 },
                { 2, 7, 4 },
                { 2, 7, 5 },
                { 2, 7, 6 },
                { 2, 7, 7 },
                { 2, 7, 8 },
                { 2, 7, 9 },
                { 2, 7, 10 },
                { 1, 8, 0 },
                { 2, 8, 0 },
                { 5, 8, 0 },
                { 1, 8, 1 },
                { 2, 8, 1 },
                { 5, 8, 1 },
                { 1, 8, 2 },
                { 2, 8, 2 },
                { 5, 8, 2 },
                { 2, 8, 3 },
                { 5, 8, 3 },
                { 2, 8, 4 },
                { 2, 8, 5 },
                { 2, 8, 6 },
                { 2, 8, 7 },
                { 2, 8, 8 },
                { 2, 8, 9 },
                { 2, 8, 10 },
                { 1, 9, 0 },
                { 2, 9, 0 },
                { 5, 9, 0 },
                { 1, 9, 1 },
                { 2, 9, 1 },
                { 5, 9, 1 },
                { 1, 9, 2 },
                { 2, 9, 2 },
                { 5, 9, 2 },
                { 2, 9, 3 },
                { 5, 9, 3 },
                { 2, 9, 4 },
                { 2, 9, 5 },
                { 2, 9, 6 },
                { 2, 9, 7 },
                { 2, 9, 8 },
                { 2, 9, 9 },
                { 2, 9, 10 },
                { 1, 10, 0 },
                { 2, 10, 0 },
                { 5, 10, 0 },
                { 1, 10, 1 },
                { 2, 10, 1 },
                { 5, 10, 1 },
                { 1, 10, 2 },
                { 2, 10, 2 },
                { 5, 10, 2 },
                { 2, 10, 3 },
                { 5, 10, 3 },
                { 2, 10, 4 },
                { 2, 10, 5 },
                { 2, 10, 6 },
                { 2, 10, 7 },
                { 2, 10, 8 },
                { 2, 10, 9 },
                { 2, 10, 10 },
                { 1, 11, 0 },
                { 5, 11, 0 },
                { 1, 11, 1 },
                { 5, 11, 1 },
                { 1, 11, 2 },
                { 5, 11, 2 },
                { 5, 11, 3 },
                { 1, 12, 0 },
                { 5, 12, 0 },
                { 1, 12, 1 },
                { 5, 12, 1 },
                { 1, 12, 2 },
                { 5, 12, 2 },
                { 5, 12, 3 },
                { 1, 13, 0 },
                { 5, 13, 0 },
                { 1, 13, 1 },
                { 5, 13, 1 },
                { 1, 13, 2 },
                { 5, 13, 2 },
                { 5, 13, 3 },
                { 1, 14, 0 },
                { 5, 14, 0 },
                { 1, 14, 1 },
                { 5, 14, 1 },
                { 1, 14, 2 },
                { 5, 14, 2 },
                { 5, 14, 3 },
                { 1, 15, 0 },
                { 5, 15, 0 },
                { 1, 15, 1 },
                { 5, 15, 1 },
                { 1, 15, 2 },
                { 5, 15, 2 },
                { 5, 15, 3 }
            });

        migrationBuilder.InsertData(
            table: "Tables",
            columns: new[] { "TableId", "LayoutId", "Status", "QrId", "PositionX", "PositionY", "Enabled" },
            values: new object[,]
            {
                { 1, 1, 2, "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b", 0, 0, true },
                { 2, 1, 0, "d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35", 2, 2, true },
                { 3, 1, 0, "4e07408562bedb8b60ce05c1decfe3ad16b72230967de01f640b7e4729b49fce", 7, 0, true },
                { 4, 1, 2, "4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a", 9, 0, true },
                { 5, 1, 1, "ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d", 11, 0, true },
                { 6, 1, 2, "e7f6c011776e8db7cd330b54174fd76f7d0216b612387a5ffcfb81e6f0919683", 13, 0, true },
                { 7, 1, 1, "7902699be42c8a8e46fbbb4501726517e86b22c56a189f7625a6da49081b2451", 15, 1, true }
            });

        migrationBuilder.InsertData(
            table: "TableCoords",
            columns: new[] { "TableId", "X", "Y" },
            values: new object[,]
            {
                { 1, 0, 0 },
                { 2, 0, 0 },
                { 3, 0, 0 },
                { 4, 0, 0 },
                { 5, 0, 0 },
                { 6, 0, 0 },
                { 7, 0, 0 },
                { 3, 0, 1 },
                { 4, 0, 1 },
                { 6, 0, 1 }
            });

        migrationBuilder.InsertData(
            table: "LayoutCoords",
            columns: new[] { "LayoutId", "X", "Y", "Type" },
            values: new object[,]
            {
                { 1, 0, 3, 0 },
                { 1, 0, 7, 0 },
                { 1, 0, 15, 0 },
                { 1, 1, 3, 0 },
                { 1, 1, 7, 0 },
                { 1, 1, 15, 0 },
                { 1, 2, 3, 0 },
                { 1, 2, 7, 0 },
                { 1, 2, 15, 0 },
                { 1, 3, 0, 0 },
                { 1, 3, 2, 0 },
                { 1, 3, 3, 0 },
                { 1, 3, 7, 0 },
                { 1, 3, 15, 1 },
                { 1, 4, 3, 0 },
                { 1, 4, 7, 0 },
                { 1, 4, 15, 0 },
                { 1, 5, 3, 1 },
                { 1, 5, 7, 0 },
                { 1, 5, 8, 0 },
                { 1, 5, 9, 1 },
                { 1, 5, 10, 0 },
                { 1, 5, 11, 0 },
                { 1, 5, 12, 0 },
                { 1, 5, 13, 0 },
                { 1, 5, 14, 0 },
                { 1, 5, 15, 0 },
                { 1, 6, 3, 1 },
                { 1, 6, 15, 0 },
                { 1, 7, 3, 0 },
                { 1, 7, 15, 1 },
                { 1, 8, 3, 0 },
                { 1, 8, 15, 0 },
                { 1, 9, 3, 0 },
                { 1, 9, 15, 0 },
                { 1, 10, 3, 0 },
                { 1, 10, 15, 0 },
                { 1, 11, 3, 0 },
                { 1, 11, 4, 0 },
                { 1, 11, 5, 1 },
                { 1, 11, 6, 0 },
                { 1, 11, 7, 0 },
                { 1, 11, 8, 0 },
                { 1, 11, 9, 0 },
                { 1, 11, 10, 0 },
                { 1, 11, 11, 0 },
                { 1, 11, 12, 0 },
                { 1, 11, 13, 0 },
                { 1, 11, 14, 0 },
                { 1, 11, 15, 0 },
                { 1, 12, 3, 0 },
                { 1, 12, 15, 0 },
                { 1, 13, 3, 0 },
                { 1, 13, 15, 0 },
                { 1, 14, 3, 0 },
                { 1, 14, 15, 0 },
                { 1, 15, 3, 0 },
                { 1, 15, 15, 0 }
            });

        migrationBuilder.InsertData(
            table: "Ingredients",
            columns: new[] { "IngredientId", "CompanyId", "Name", "Stock", "Alert", "Unit", "Enabled" },
            values: new object[,]
            {
                { 1, 1, "Harina 000", 50m, 10, 0, true },
                { 2, 1, "Tomate fresco", 30m, 5, 0, true },
                { 3, 1, "Queso mozzarela", 20m, 3, 0, true },
                { 4, 1, "Aceite de oliva", 15m, 2, 4, true },
                { 5, 1, "Cebolla", 3m, 4, 0, true },
                { 6, 1, "Pollo", 10m, 2, 0, true },
                { 7, 1, "Pasta seca", 40m, 8, 0, true },
                { 8, 1, "Salsa de tom ", 12m, 2, 4, true },
                { 9, 1, "Albaca", 200m, 50, 1, true },
                { 10, 1, "Vino tinto", 8m, 1, 4, true }
            });

        // Parent products (with CategoryId, null ParentId)
        migrationBuilder.InsertData(
            table: "Products",
            columns: new[] { "ProductId", "CompanyId", "CategoryId", "ParentId", "Name", "Description", "Price", "Enabled" },
            values: new object[,]
            {
                { 1, 1, 1, null, "Café", "(de corte origen brasil)", 0m, true },
                { 2, 1, 1, null, "Especial del día", "(consultar origen)", 1000m, true },
                { 3, 1, 1, null, "Frío", "", 0m, true },
                { 4, 1, 2, null, "Croissant", "", 0m, true },
                { 5, 1, 2, null, "Budines", "", 0m, true },
                { 6, 1, 2, null, "Galletas", "", 0m, true },
                { 7, 1, 2, null, "Sin TACC", "", 0m, true },
                { 8, 1, 3, null, "Sandwiches", "", 0m, true },
                { 9, 1, 3, null, "Tostones", "", 0m, true },
                { 10, 1, 4, null, "Completo", "Infusion, tostadas de pan de campo y pan de molde, jamon cocido, queso tybo, huevo revuelto con semillas, queso crema y un bowl con yogurt natural, miel y granola", 1000m, true },
                { 11, 1, 4, null, "Lightweight", "Infusión tostadas de pan de molde, pulpa de tomate y oliva y bowl con yogurt natural, miel, frutas de estación y granola.", 1000m, true },
                { 12, 1, 4, null, "Baby breakfast", "Infusión,panqueques de avena y banana con miel, frutos secos y frutas de estación", 1000m, true },
                { 13, 1, 5, null, "Tartas", "", 0m, true },
                { 14, 1, 5, null, "Wrap", "", 0m, true },
                { 15, 1, 5, null, "Ensaladas", "", 0m, true },
                { 16, 1, 6, null, "Naturales", "", 0m, true },
                { 17, 1, 6, null, "Otras bebidas", "", 0m, true },
                { 18, 1, 7, null, "Vermút", "(Aperitivo a base de hierbas y especias acompañado con dash de soda, hielo y rodaja de naranja)", 1000m, true },
                { 19, 1, 7, null, "Gin tonic", "(Destilado inglés acompañado con tónica, hielo y rodaja de limón)", 1000m, true },
                { 20, 1, 7, null, "Aperol Spritz", "(Aperol, vino espumante extra brut, dash de soda y rodaja de naranja)", 1000m, true },
                { 21, 1, 7, null, "Negroni", "(Vermút, gin, campari y rodaja de naranja)", 1000m, true }
            });

        // Child products (null CategoryId, with ParentId)
        migrationBuilder.InsertData(
            table: "Products",
            columns: new[] { "ProductId", "CompanyId", "CategoryId", "ParentId", "Name", "Description", "Price", "Enabled" },
            values: new object[,]
            {
                { 22, 1, null, 1, "Espresso", "", 1000m, true },
                { 23, 1, null, 1, "Espresso macchiato", "", 1000m, true },
                { 24, 1, null, 1, "Doppio", "", 1000m, true },
                { 25, 1, null, 1, "Lungo", "", 1000m, true },
                { 26, 1, null, 1, "Americano simple/doble", "", 1000m, true },
                { 27, 1, null, 1, "Cortado", "", 1000m, true },
                { 28, 1, null, 1, "Flat White", "", 1000m, true },
                { 29, 1, null, 1, "Capuchino", "", 1000m, true },
                { 30, 1, null, 1, "Latte", "", 1000m, true },
                { 31, 1, null, 1, "Moca", "", 1000m, true },
                { 32, 1, null, 1, "Caramel Latte", "", 1000m, true },
                { 33, 1, null, 1, "Vanilla latte", "", 1000m, true },
                { 34, 1, null, 1, "Avellana latte", "", 1000m, true },
                { 35, 1, null, 1, "Nutella latte", "Chocolate especial con pasta de avellanas", 1000m, true },
                { 36, 1, null, 3, "Espresso con hielo", "", 1000m, true },
                { 37, 1, null, 3, "Espresso tonic", "", 1000m, true },
                { 38, 1, null, 3, "Cold Flat", "", 1000m, true },
                { 39, 1, null, 3, "Iced Latte", "", 1000m, true },
                { 40, 1, null, 3, "Iced caramel latte", "", 1000m, true },
                { 41, 1, null, 3, "Iced vanilla latte", "", 1000m, true },
                { 42, 1, null, 3, "Iced avellana latte", "", 1000m, true },
                { 43, 1, null, 3, "Iced americano simple/doble", "", 1000m, true },
                { 44, 1, null, 4, "Con jamon cocido y queso tybo", "", 1000m, true },
                { 45, 1, null, 4, "Con rucula, tomates secos, queso parmesano y oliva", "", 1000m, true },
                { 46, 1, null, 4, "Con dulce de leche y azucar impalpable", "", 1000m, true },
                { 47, 1, null, 4, "Con nutella y azucar impalpable", "", 1000m, true },
                { 48, 1, null, 4, "Croissant", "", 1000m, true },
                { 49, 1, null, 4, "Pain au chocolat", "", 1000m, true },
                { 50, 1, null, 4, "Roll de canela", "", 1000m, true },
                { 51, 1, null, 5, "Zanahoria", "", 1000m, true },
                { 52, 1, null, 5, "Limon y amapolas", "", 1000m, true },
                { 53, 1, null, 5, "Avellanas y chocolate (vegano)", "", 1000m, true },
                { 54, 1, null, 5, "Banana y tahini", "", 1000m, true },
                { 55, 1, null, 6, "Almendras coco y chocolate negro.", "", 1000m, true },
                { 56, 1, null, 6, "Limón chocolate blanco y pistacho.", "", 1000m, true },
                { 57, 1, null, 6, "Chocolate con sal (vegana)", "", 1000m, true },
                { 58, 1, null, 6, "Alfajor de nuez.", "", 1000m, true },
                { 59, 1, null, 6, "Scones de queso y pimienta", "", 1000m, true },
                { 60, 1, null, 6, "Scones de queso y verdeo", "", 1000m, true },
                { 61, 1, null, 6, "Chipa", "", 1000m, true },
                { 62, 1, null, 7, "Alfajorcito de mani con dulce de leche y sésamo", "", 1000m, true },
                { 63, 1, null, 7, "Alfajorcito de mani con chocolate y dulce de leche", "", 1000m, true },
                { 64, 1, null, 7, "Alfajorcito de maicena", "", 1000m, true },
                { 65, 1, null, 7, "Pepas (2 unidades)", "", 1000m, true },
                { 66, 1, null, 7, "Conito de dulce de leche", "", 1000m, true },
                { 67, 1, null, 8, "Catalan", "Jamón cocido y queso tybo con pulpa de tomate en pan baguette.", 1000m, true },
                { 68, 1, null, 8, "Mediterraneo", "Rucula, toates cherry confitados, queso tybo, pesto de albahaca, aceitunas negras en pan baguette.", 1000m, true },
                { 69, 1, null, 8, "Vegetariano", "Mix de hojas verdes, cherry confitado, zucchini, queso tybo, pepino, mayo de zanahorias, en pan ciabatta.", 1000m, true },
                { 70, 1, null, 8, "Pauza", "Lomito ahumado, rúcula, pimientossalteados, cebolla caramelizada, parmesano y lactonesa de hierbas en pan ciabatta", 1000m, true },
                { 71, 1, null, 8, "Sandwich Croque Monsieur", "Jamón cocido, queso tybo en pan de molde con salsa bechamel y queso gratinado.", 1000m, true },
                { 72, 1, null, 8, "Sandwich Croque Madame", "Jamón cocido, queso tybo en pan de molde con salsa bechamel,queso gratinado y huevo frito.", 1000m, true },
                { 73, 1, null, 8, "Bagel", "Lomito ahumado, queso tybo y huevo.", 1000m, true },
                { 74, 1, null, 9, "De pan de molde con mermelada/miel y queso crema/ manteca.", "", 1000m, true },
                { 75, 1, null, 9, "De pan de campo con pulpa de tomate, queso parmesano y pesto de albahaca.", "", 1000m, true },
                { 76, 1, null, 9, "De pan de campo con queso crema, palta y huevo revuelto.", "", 1000m, true },
                { 77, 1, null, 9, "De hogaza maíz morado con queso crema, palta, brotes de lenteja y semillas.", "", 1000m, true },
                { 78, 1, null, 9, "Francesa con fruta de estación y granola con culis de naranja y menta.", "", 1000m, true },
                { 79, 1, null, 9, "Yogurt con granola, frutas de estación y miel", "", 1000m, true },
                { 80, 1, null, 13, "Tarta veggie", "Espuma de espinaca concubos de calabacin y choclo salteado, tomate cherry,cebollacaramelizada en masa quebrada.", 1000m, true },
                { 81, 1, null, 13, "Tarta gourmet", "Pollo, cebollas caramelizadas, espinaca, queso azul y nueces en masa quebrada.", 1000m, true },
                { 82, 1, null, 14, "Wrap frio", "Tortilla de trigo , mix de verdes, palta, zanahoria, pollo y pate de remolacha y semillas.", 1000m, true },
                { 83, 1, null, 14, "Wrap calentito", "Tortilla de trigo calentita, pollo, queso tybo, cebolla caramelizada, zanahoria, pimiento rojo y verde, con mostaza Pauza (mostaza, curry y miel).", 1000m, true },
                { 84, 1, null, 15, "Cesar", "Lechuga manteca, tomates cherry confitados, jamon cocido y queso tybo en tiras, crutones y pollo al horno con salsa césar", 1000m, true },
                { 85, 1, null, 15, "Pauza", "Mix de verdes, zanahoria, pepino, cherry confitados, crutones, brotes de lenteja, acompañado con vinagreta de yogurt natural", 1000m, true },
                { 86, 1, null, 16, "Limonada menta y jengibre 1/2L.", "", 1000m, true },
                { 87, 1, null, 16, "Jugo de naranja exprimido", "", 1000m, true },
                { 88, 1, null, 17, "Gaseosa lata 330 cc", "", 1000m, true },
                { 89, 1, null, 17, "Agua mineal 500 cc", "", 1000m, true },
                { 90, 1, null, 17, "Agua mineral con gas 500 cc", "", 1000m, true },
                { 91, 1, null, 17, "Stella Artois 330 cc", "", 1000m, true },
                { 92, 1, null, 17, "Sidra Peer", "", 1000m, true },
                { 93, 1, null, 18, "Cinzano Rosso/Bianco", "", 0m, true },
                { 94, 1, null, 18, "Lunfa", "", 0m, true },
                { 95, 1, null, 18, "Lunfa Verbena", "", 0m, true },
                { 96, 1, null, 18, "La Fuerza Rojo/Blanco", "", 0m, true },
                { 97, 1, null, 19, "Brokers", "", 0m, true },
                { 98, 1, null, 19, "Tanqueray", "", 0m, true }
            });

        // Advance identity sequences so next inserts get IDs after the seed data
        migrationBuilder.Sql(@"
ALTER TABLE ""Users"" ALTER COLUMN ""UserId"" RESTART WITH 2;
ALTER TABLE ""Companies"" ALTER COLUMN ""CompanyId"" RESTART WITH 2;
ALTER TABLE ""Categories"" ALTER COLUMN ""CategoryId"" RESTART WITH 8;
ALTER TABLE ""Premises"" ALTER COLUMN ""PremiseId"" RESTART WITH 2;
ALTER TABLE ""Layouts"" ALTER COLUMN ""LayoutId"" RESTART WITH 2;
ALTER TABLE ""Sectors"" ALTER COLUMN ""SectorId"" RESTART WITH 6;
ALTER TABLE ""Tables"" ALTER COLUMN ""TableId"" RESTART WITH 8;
ALTER TABLE ""Ingredients"" ALTER COLUMN ""IngredientId"" RESTART WITH 11;
ALTER TABLE ""Products"" ALTER COLUMN ""ProductId"" RESTART WITH 99;
");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
DELETE FROM ""Products"" WHERE ""CompanyId"" = 1;
DELETE FROM ""Ingredients"" WHERE ""CompanyId"" = 1;
DELETE FROM ""Companies"" WHERE ""CompanyId"" = 1;
DELETE FROM ""Users"" WHERE ""UserId"" = 1;
");
    }
}
